services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: jwt-app-db2
    volumes:
      - postgres-data:/var/lib/postgresql/data

  server:
    build: ./server
    command: npm run dev
    restart: unless-stopped
    ports:
      - '${AUTH_SERVER_PORT}:${AUTH_SERVER_PORT}'
      - '${POSTS_SERVER_PORT}:${POSTS_SERVER_PORT}'
    environment:
      - AUTH_SERVER_PORT=${AUTH_SERVER_PORT}
      - POSTS_SERVER_PORT=${POSTS_SERVER_PORT}
      - CLIENT_PORT=${CLIENT_PORT}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres

  client:
    build: ./client
    command: npm run dev
    restart: unless-stopped
    ports:
      - '${CLIENT_PORT}:${CLIENT_PORT}'
    environment:
      - CLIENT_PORT=${CLIENT_PORT}

volumes:
  postgres-data:
